### ISSUE TITLE
Баг в продакшне

### ISSUE THREAD

**Issue by yazonnile** [kobezzza/Collection#3]
Использовал пока только 1 функцию из библиотеки

``` js
import { extend } from 'collection.js';
```

Эта строчка ломает продакшн сборку. Код не минифается. Без строчки - минифается.

Вебпак. Минифай обычный Uglify плагином

**Comment by kobezzza** [comment]
Можно больше информации, а то я чёто туплю)

**Comment by yazonnile** [comment]
В одном из редьюсеров понадобился deepExtend
Взял для этого функцию из этой библиотеки. И после этого отвалилась в частности минификация, которую делает аглифай вебпак плагин. Комменчу строчку подключения коллекшн -все ок, код минифицируется. Возвращаю - минификация несрабатывает.
Сейчас с планшета. Как мог описал. Завтра подробнее, если надо будет:)

**Comment by kobezzza** [comment]
Думаю дело в том, что при таком подключении включается ES6 версия Collection для ноды (аглифай не умеет ES6), замени на `'collection.js/compiled'`.

**Comment by yazonnile** [comment]
К сожалению, нет. Тоже самое.

``` js
import { extend } from 'collection.js/compiled';
```

Закомментил строчку - все ок. Раскомментил - код не минифается. Когда будет время - попробую минимальную конфигурацию слепить, чтобы повторить проблему

**Comment by kobezzza** [comment]
Ну вообще, я не тестил ES6 подключение, и более того не уверен, что оно в принципе поддерживается. Вообще Collection не надо лепить вместе с основными файлами и подключать отдельно уже сжатую (с хитрыми оптимизациями) версию ДО всех остальных подключений.

``` js
const $C = require('collection.js');
$C.extend(true, { ... }, { ... });
```

А вообще, если нужен один экстендинг, мб лучше Sugar использовать? А то получается из пушки по воробьям)

**Comment by bonkalol** [comment]
Тоже хотел так экспортнуть, а не получилось, капец конечно...
Таска с 2016 года... И автору не стыдно ведь... хоть закрыл бы...

**Comment by kobezzza** [comment]
ахах :) Чтобы так работало, нужно доработать архитектуру библиотеки.
